import React, { useEffect, useState, useRef } from 'react'
import toast from 'react-hot-toast'
import { FlaskConical, Play, Download, RefreshCw, Plus, Eye, Trash2, CheckCircle, XCircle, Clock, Cpu, Zap, BarChart2, GitCompare, Send } from 'lucide-react'
import { PageHeader } from '../components/layout/Layout'
import { Card, CardHeader, Btn, Badge, Modal, Spinner, Empty, SectionLabel, StatusDot } from '../components/ui'
import { PageHelp, Hint } from '../components/help'
import { useStore } from '../hooks/useStore'
import api from '../api'

const JOB_STATUS_COLOR = {
  queued: 'default', pending_approval: 'amber', launching: 'amber',
  running: 'blue', done: 'green', error: 'red', cancelled: 'default',
}

// ── Tab switcher ──────────────────────────────────────────────────────────────
function Tabs({ tabs, active, onChange }) {
  return (
    <div style={{ display: 'flex', gap: 2, marginBottom: 20, background: 'var(--bg-raised)', borderRadius: 'var(--radius-lg)', padding: 3, width: 'fit-content', border: '1px solid var(--border)' }}>
      {tabs.map(t => (
        <button key={t.id} onClick={() => onChange(t.id)} style={{
          padding: '6px 16px', borderRadius: 'var(--radius)', fontSize: 12,
          fontFamily: 'var(--font-mono)', cursor: 'pointer', border: 'none',
          background: active === t.id ? 'var(--bg-overlay)' : 'transparent',
          color: active === t.id ? 'var(--accent)' : 'var(--text-muted)',
          transition: 'all 0.12s',
        }}>{t.icon} {t.label}</button>
      ))}
    </div>
  )
}

// ── Dataset Builder ───────────────────────────────────────────────────────────
function DatasetBuilder({ collections, models, onRefresh }) {
  const [datasets, setDatasets] = useState([])
  const [loading, setLoading] = useState(true)
  const [createModal, setCreateModal] = useState(false)
  const [previewModal, setPreviewModal] = useState({ open: false, rows: [], total: 0, format: '' })
  const [form, setForm] = useState({
    name: '', description: '', source_id: '', format: 'alpaca',
    model: '', pairs_per_chunk: 3, prompt_type: 'general', system_prompt: '',
  })

  const refresh = async () => {
    try {
      const r = await api.get('/finetune/datasets')
      setDatasets(r.data || [])
    } catch { toast.error('Failed to load datasets') }
    finally { setLoading(false) }
  }

  useEffect(() => { refresh() }, [])

  const handleCreate = async () => {
    if (!form.name || !form.model || !form.source_id) return toast.error('Name, model, and KB required')
    try {
      await api.post('/finetune/datasets', { ...form, source_type: 'kb_collection' })
      toast.success('Dataset generation started — watch status below')
      setCreateModal(false)
      setForm({ name: '', description: '', source_id: '', format: 'alpaca', model: '', pairs_per_chunk: 3, prompt_type: 'general', system_prompt: '' })
      refresh()
    } catch (e) { toast.error(e.response?.data?.detail || 'Create failed') }
  }

  const handlePreview = async (ds) => {
    try {
      const r = await api.get(`/finetune/datasets/${ds.id}/preview`)
      setPreviewModal({ open: true, rows: r.data.rows, total: r.data.total, format: r.data.format })
    } catch { toast.error('Preview failed') }
  }

  const handleDelete = async (id) => {
    if (!confirm('Delete this dataset?')) return
    await api.delete(`/finetune/datasets/${id}`)
    refresh()
  }

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
        <div style={{ fontFamily: 'var(--font-display)', fontWeight: 600, fontSize: 14 }}>Training Datasets</div>
        <div style={{ display: 'flex', gap: 8 }}>
          <Btn size="sm" variant="ghost" onClick={refresh}><RefreshCw size={11} /></Btn>
          <Btn size="sm" variant="accent" onClick={() => setCreateModal(true)}><Plus size={11} /> New Dataset</Btn>
        </div>
      </div>

      <Hint type="tip" dismissible>
        Datasets are generated by asking your local LLM to create Q&A pairs from each chunk of a KB collection.
        No GPU needed for this step — just Ollama. Use 2-5 pairs/chunk for good coverage without noise.
      </Hint>

      {loading ? <Spinner /> : datasets.length === 0 ? (
        <Empty icon="🗂️" title="No datasets" description="Create one from a KB collection to start fine-tuning." />
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginTop: 12 }}>
          {datasets.map(ds => (
            <div key={ds.id} style={{
              display: 'flex', alignItems: 'center', gap: 12,
              padding: '12px 16px', background: 'var(--bg-surface)',
              border: '1px solid var(--border)', borderRadius: 'var(--radius-lg)',
            }}>
              <div style={{ flex: 1 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 3 }}>
                  <span style={{ fontFamily: 'var(--font-display)', fontWeight: 600, fontSize: 13 }}>{ds.name}</span>
                  <Badge color={ds.status === 'ready' ? 'green' : ds.status === 'error' ? 'red' : ds.status === 'generating' ? 'blue' : 'amber'}>{ds.status}</Badge>
                  <Badge color="default">{ds.format}</Badge>
                </div>
                <div style={{ fontSize: 11, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
                  {ds.row_count} pairs · model: {ds.model_used} · {new Date(ds.created_at).toLocaleDateString()}
                </div>
              </div>
              <div style={{ display: 'flex', gap: 6 }}>
                {ds.status === 'ready' && <Btn size="sm" variant="ghost" onClick={() => handlePreview(ds)}><Eye size={11} /> preview</Btn>}
                <Btn size="sm" variant="ghost" onClick={() => handleDelete(ds.id)}><Trash2 size={11} style={{ color: 'var(--red)' }} /></Btn>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Create modal */}
      <Modal open={createModal} onClose={() => setCreateModal(false)} title="Generate Dataset from KB" width={520}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          <Hint type="info">Your local LLM will read each KB chunk and generate question-answer pairs automatically. This may take 5-30 minutes depending on KB size.</Hint>
          {[
            { label: 'Dataset name', key: 'name', placeholder: 'e.g. pentest_qa_v1' },
            { label: 'Description', key: 'description', placeholder: 'Optional' },
          ].map(f => (
            <div key={f.key} style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
              <label style={{ fontSize: 11, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>{f.label}</label>
              <input value={form[f.key]} onChange={e => setForm(p => ({...p, [f.key]: e.target.value}))} placeholder={f.placeholder}
                style={{ padding: '7px 10px', borderRadius: 'var(--radius)', border: '1px solid var(--border-mid)', background: 'var(--bg-raised)', color: 'var(--text-primary)', fontSize: 12, fontFamily: 'var(--font-mono)' }} />
            </div>
          ))}
          {[
            { label: 'KB Collection', key: 'source_id', options: collections.map(c => ({ value: c.id, label: `${c.name} (${c.doc_count} chunks)` })), placeholder: 'Select collection…' },
            { label: 'Generator Model', key: 'model', options: models.filter(m => !m.name.includes('embed')).map(m => ({ value: m.name, label: m.name })), placeholder: 'Select model…' },
            { label: 'Output Format', key: 'format', options: [{ value: 'alpaca', label: 'Alpaca (instruction tuning)' }, { value: 'chatml', label: 'ChatML (conversation)' }, { value: 'sharegpt', label: 'ShareGPT (multi-turn)' }] },
            { label: 'Prompt Style', key: 'prompt_type', options: [{ value: 'general', label: 'General' }, { value: 'pentest', label: 'Pentest / Security' }, { value: 'technical', label: 'Technical Docs' }] },
          ].map(f => (
            <div key={f.key} style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
              <label style={{ fontSize: 11, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>{f.label}</label>
              <select value={form[f.key]} onChange={e => setForm(p => ({...p, [f.key]: e.target.value}))}
                style={{ padding: '7px 10px', borderRadius: 'var(--radius)', border: '1px solid var(--border-mid)', background: 'var(--bg-raised)', color: 'var(--text-primary)', fontSize: 12, fontFamily: 'var(--font-mono)' }}>
                {f.placeholder && <option value="">{f.placeholder}</option>}
                {f.options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
              </select>
            </div>
          ))}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
            <label style={{ fontSize: 11, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>Pairs per chunk <span style={{ color: 'var(--text-muted)', textTransform: 'none' }}>({form.pairs_per_chunk})</span></label>
            <input type="range" min="1" max="10" value={form.pairs_per_chunk} onChange={e => setForm(p => ({...p, pairs_per_chunk: parseInt(e.target.value)}))}
              style={{ accentColor: 'var(--accent)' }} />
            <div style={{ fontSize: 10, color: 'var(--text-muted)' }}>Recommended: 2-5. More = richer dataset but slower generation.</div>
          </div>
          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}>
            <Btn variant="ghost" onClick={() => setCreateModal(false)}>cancel</Btn>
            <Btn variant="accent" onClick={handleCreate}><Zap size={11} /> Generate Dataset</Btn>
          </div>
        </div>
      </Modal>

      {/* Preview modal */}
      <Modal open={previewModal.open} onClose={() => setPreviewModal({ open: false })} title={`Dataset Preview — ${previewModal.format}`} width={620}>
        <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 10 }}>Showing first {previewModal.rows.length} of {previewModal.total} rows</div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8, maxHeight: 400, overflow: 'auto' }}>
          {previewModal.rows.map((row, i) => (
            <div key={i} style={{ background: 'var(--bg-raised)', borderRadius: 'var(--radius)', padding: '10px 12px', border: '1px solid var(--border)', fontSize: 11 }}>
              {row.instruction && <>
                <div style={{ color: 'var(--accent)', marginBottom: 4 }}>Q: {row.instruction}</div>
                <div style={{ color: 'var(--text-secondary)' }}>A: {row.output?.slice(0, 200)}{row.output?.length > 200 ? '…' : ''}</div>
              </>}
              {row.messages && row.messages.map((m, j) => (
                <div key={j} style={{ color: m.role === 'user' ? 'var(--accent)' : 'var(--text-secondary)', marginBottom: 2 }}>
                  <span style={{ fontWeight: 600 }}>{m.role}: </span>{m.content?.slice(0, 150)}
                </div>
              ))}
            </div>
          ))}
        </div>
      </Modal>
    </div>
  )
}

// ── Fine-tune Jobs ────────────────────────────────────────────────────────────
function FineTuneJobs({ models }) {
  const [jobs, setJobs] = useState([])
  const [datasets, setDatasets] = useState([])
  const [loading, setLoading] = useState(true)
  const [unsloth, setUnsloth] = useState(null)
  const [createModal, setCreateModal] = useState(false)
  const [logsModal, setLogsModal] = useState({ open: false, job: null, logs: '', metrics: null })
  const [form, setForm] = useState({ name: '', base_model: '', dataset_id: '', method: 'lora' })

  const refresh = async () => {
    try {
      const [j, d] = await Promise.all([api.get('/finetune/jobs'), api.get('/finetune/datasets')])
      setJobs(j.data || [])
      setDatasets((d.data || []).filter(d => d.status === 'ready'))
    } catch {}
    finally { setLoading(false) }
  }

  useEffect(() => {
    refresh()
    const t = setInterval(refresh, 8000)
    api.get('/docker/unsloth/status').then(r => setUnsloth(r.data)).catch(() => {})
    return () => clearInterval(t)
  }, [])

  const handleCreate = async () => {
    if (!form.name || !form.base_model || !form.dataset_id) return toast.error('All fields required')
    try {
      const r = await api.post('/finetune/jobs', form)
      toast.success(`Job queued. Approval ID: ${r.data.approval_request_id?.slice(0, 8)}… — approve in Approvals tab`)
      setCreateModal(false)
      refresh()
    } catch (e) { toast.error(e.response?.data?.detail || 'Create failed') }
  }

  const handleLaunch = async (job) => {
    try {
      await api.post(`/finetune/jobs/${job.id}/launch`)
      toast.success('Job launching…')
      refresh()
    } catch (e) { toast.error(e.response?.data?.detail || 'Launch failed') }
  }

  const handleLogs = async (job) => {
    setLogsModal({ open: true, job, logs: 'Loading…', metrics: null })
    try {
      const r = await api.get(`/finetune/jobs/${job.id}/logs`)
      setLogsModal(s => ({ ...s, logs: r.data.logs, metrics: r.data.metrics }))
    } catch { setLogsModal(s => ({ ...s, logs: '(failed to fetch)' })) }
  }

  const handleExportGGUF = async (job) => {
    try {
      const r = await api.post(`/finetune/jobs/${job.id}/export-gguf?quantization=q4_k_m`)
      toast.success(`GGUF export queued. Approve in Approvals tab.`)
    } catch (e) { toast.error(e.response?.data?.detail || 'Export failed') }
  }

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
        <div style={{ fontFamily: 'var(--font-display)', fontWeight: 600, fontSize: 14 }}>Fine-Tune Jobs</div>
        <div style={{ display: 'flex', gap: 8 }}>
          <Btn size="sm" variant="ghost" onClick={refresh}><RefreshCw size={11} /></Btn>
          <Btn size="sm" variant="accent" onClick={() => setCreateModal(true)}><Plus size={11} /> New Job</Btn>
        </div>
      </div>

            <div style={{
        padding: '12px 16px', marginBottom: 12,
        background: 'var(--bg-raised)',
        border: '1px solid var(--border)',
        borderRadius: 'var(--radius-lg)',
        display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16,
      }}>
        <div>
          <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-primary)', marginBottom: 6 }}>
            📦 Unsloth Docker Image
          </div>
          <div style={{ fontSize: 11, color: 'var(--text-secondary)', lineHeight: 1.6, marginBottom: 8 }}>
            Fine-tune jobs run inside the Unsloth Docker image. Pull it once before your first job.
          </div>
          <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, padding: '6px 10px',
            background: 'var(--bg-base)', borderRadius: 'var(--radius)', color: 'var(--accent)',
            border: '1px solid var(--border-mid)', marginBottom: 6 }}>
            docker pull unsloth/unsloth-repo:latest
          </div>
          <div style={{ fontSize: 10, color: 'var(--text-muted)' }}>
            ~8GB download. Do this once on your dev machine.
          </div>
        </div>
        <div>
          <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-primary)', marginBottom: 6 }}>
            🖥️ Your Setup (CPU mode)
          </div>
          <div style={{ fontSize: 11, color: 'var(--text-secondary)', lineHeight: 1.6 }}>
            Settings → Compute → Device is set to <code style={{ color: 'var(--amber)', fontFamily: 'var(--font-mono)' }}>cpu</code>.
            CPU fine-tuning works but is very slow — good for testing the pipeline.
            For production: use a machine with NVIDIA GPU and set device to <code style={{ color: 'var(--green)', fontFamily: 'var(--font-mono)' }}>cuda</code>.
          </div>
          <div style={{ marginTop: 8 }}>
            <Btn size="sm" variant="ghost" onClick={() => window.location.href = '/settings'}>
              ⚙️ Open Settings
            </Btn>
          </div>
        </div>
      </div>

      {/* Unsloth image status */}
      {unsloth && (
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8, fontSize: 11 }}>
          <div style={{
            padding: '3px 10px', borderRadius: 20,
            background: unsloth.available ? 'rgba(61,214,140,0.1)' : 'rgba(245,166,35,0.1)',
            border: `1px solid ${unsloth.available ? 'rgba(61,214,140,0.3)' : 'rgba(245,166,35,0.3)'}`,
            color: unsloth.available ? 'var(--green)' : 'var(--amber)',
          }}>
            {unsloth.available
              ? `✓ Unsloth image ready (${unsloth.images?.[0]?.size_gb}GB)`
              : `⚠ Unsloth not pulled — run: docker pull unsloth/unsloth-repo:latest`}
          </div>
        </div>
      )}
      {loading ? <Spinner /> : jobs.length === 0 ? (
        <Empty icon="⚗️" title="No fine-tune jobs" description="Create a job once you have a ready dataset." />
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginTop: 12 }}>
          {jobs.map(job => (
            <div key={job.id} style={{ padding: '13px 16px', background: 'var(--bg-surface)', border: '1px solid var(--border)', borderRadius: 'var(--radius-lg)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                <StatusDot status={job.status === 'running' ? 'running' : job.status === 'done' ? 'online' : job.status === 'error' ? 'error' : 'staged'} />
                <div style={{ flex: 1 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 3 }}>
                    <span style={{ fontFamily: 'var(--font-display)', fontWeight: 600, fontSize: 13 }}>{job.name}</span>
                    <Badge color={JOB_STATUS_COLOR[job.status] || 'default'}>{job.status}</Badge>
                    <Badge color="default">{job.method}</Badge>
                  </div>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
                    base: {job.base_model} {job.metrics?.final_loss ? `· loss: ${job.metrics.final_loss.toFixed(4)}` : ''}
                    {job.ollama_imported && ` · ollama: ${job.ollama_imported}`}
                  </div>
                </div>
                <div style={{ display: 'flex', gap: 6 }}>
                  <Btn size="sm" variant="ghost" onClick={() => handleLogs(job)}><BarChart2 size={11} /> logs</Btn>
                  {job.status === 'pending_approval' && <Btn size="sm" variant="success" onClick={() => handleLaunch(job)}><Play size={11} /> launch</Btn>}
                  {job.status === 'done' && !job.gguf_path && <Btn size="sm" variant="ghost" onClick={() => handleExportGGUF(job)}><Download size={11} /> export GGUF</Btn>}
                  {job.ollama_imported && <Badge color="green">in Ollama</Badge>}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Create modal */}
      <Modal open={createModal} onClose={() => setCreateModal(false)} title="New Fine-Tune Job" width={500}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          <Hint type="info">Job will be queued for owner approval before launching. The training runs in an Unsloth Docker container.</Hint>
          {[
            { label: 'Job Name', key: 'name', placeholder: 'e.g. pentest_lora_v1' },
          ].map(f => (
            <div key={f.key} style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
              <label style={{ fontSize: 11, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>{f.label}</label>
              <input value={form[f.key]} onChange={e => setForm(p => ({...p, [f.key]: e.target.value}))} placeholder={f.placeholder}
                style={{ padding: '7px 10px', borderRadius: 'var(--radius)', border: '1px solid var(--border-mid)', background: 'var(--bg-raised)', color: 'var(--text-primary)', fontSize: 12, fontFamily: 'var(--font-mono)' }} />
            </div>
          ))}
          {[
            { label: 'Base Model (Ollama)', key: 'base_model', options: models.filter(m => !m.name.includes('embed')).map(m => ({ value: m.name, label: m.name })) },
            { label: 'Training Dataset', key: 'dataset_id', options: datasets.map(d => ({ value: d.id, label: `${d.name} (${d.row_count} rows)` })) },
            { label: 'Method', key: 'method', options: [{ value: 'lora', label: 'LoRA — fast, low VRAM (recommended)' }, { value: 'qlora', label: 'QLoRA — 4-bit, minimal VRAM' }, { value: 'full', label: 'Full fine-tune — needs lots of VRAM' }] },
          ].map(f => (
            <div key={f.key} style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
              <label style={{ fontSize: 11, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>{f.label}</label>
              <select value={form[f.key]} onChange={e => setForm(p => ({...p, [f.key]: e.target.value}))}
                style={{ padding: '7px 10px', borderRadius: 'var(--radius)', border: '1px solid var(--border-mid)', background: 'var(--bg-raised)', color: 'var(--text-primary)', fontSize: 12, fontFamily: 'var(--font-mono)' }}>
                <option value="">Select…</option>
                {f.options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
              </select>
            </div>
          ))}
          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}>
            <Btn variant="ghost" onClick={() => setCreateModal(false)}>cancel</Btn>
            <Btn variant="accent" onClick={handleCreate}><FlaskConical size={11} /> Queue Job</Btn>
          </div>
        </div>
      </Modal>

      {/* Logs modal */}
      <Modal open={logsModal.open} onClose={() => setLogsModal({ open: false })} title={`Logs: ${logsModal.job?.name}`} width={640}>
        {logsModal.metrics && (
          <div style={{ display: 'flex', gap: 10, marginBottom: 12 }}>
            {Object.entries(logsModal.metrics).map(([k, v]) => (
              <div key={k} style={{ padding: '6px 12px', background: 'var(--bg-raised)', borderRadius: 'var(--radius)', fontSize: 11 }}>
                <span style={{ color: 'var(--text-muted)' }}>{k}: </span>
                <span style={{ color: 'var(--accent)', fontFamily: 'var(--font-mono)' }}>{typeof v === 'number' ? v.toFixed(4) : v}</span>
              </div>
            ))}
          </div>
        )}
        <pre style={{ fontSize: 10, fontFamily: 'var(--font-mono)', background: 'var(--bg-base)', borderRadius: 'var(--radius)', padding: 12, maxHeight: 400, overflow: 'auto', color: 'var(--text-secondary)', lineHeight: 1.5, border: '1px solid var(--border)', whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>
          {logsModal.logs}
        </pre>
      </Modal>
    </div>
  )
}

// ── Model Arena ───────────────────────────────────────────────────────────────
function ModelArena({ models, collections }) {
  const [modelA, setModelA] = useState('')
  const [modelB, setModelB] = useState('')
  const [kbA, setKbA] = useState('')
  const [kbB, setKbB] = useState('')
  const [prompt, setPrompt] = useState('')
  const [responseA, setResponseA] = useState(null)
  const [responseB, setResponseB] = useState(null)
  const [loadingA, setLoadingA] = useState(false)
  const [loadingB, setLoadingB] = useState(false)

  const run = async () => {
    if (!prompt.trim()) return toast.error('Enter a prompt')
    if (!modelA && !modelB) return toast.error('Select at least one model')

    const query = async (model, kbId, setLoading, setResponse) => {
      if (!model) return
      setLoading(true); setResponse(null)
      try {
        const r = await api.post('/chat/', {
          model,
          message: prompt,
          kb_collection_id: kbId || null,
          stream: false,
        })
        setResponse({ reply: r.data.reply, sources: r.data.sources, rag: r.data.rag_used, tokens: r.data.tokens })
      } catch (e) {
        setResponse({ error: e.response?.data?.detail || e.message })
      } finally { setLoading(false) }
    }

    query(modelA, kbA, setLoadingA, setResponseA)
    query(modelB, kbB, setLoadingB, setResponseB)
  }

  const chatModels = models.filter(m => !m.name.includes('embed'))

  return (
    <div>
      <div style={{ fontFamily: 'var(--font-display)', fontWeight: 600, fontSize: 14, marginBottom: 14 }}>Model Arena — Side-by-Side Comparison</div>
      <Hint type="tip" dismissible>Compare a base model vs your fine-tuned model, or two different models on the same KB. Useful for evaluating fine-tune quality.</Hint>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14, marginTop: 12, marginBottom: 16 }}>
        {[
          { label: 'Model A', model: modelA, setModel: setModelA, kb: kbA, setKb: setKbA, response: responseA, loading: loadingA, color: 'var(--blue)' },
          { label: 'Model B', model: modelB, setModel: setModelB, kb: kbB, setKb: setKbB, response: responseB, loading: loadingB, color: 'var(--accent)' },
        ].map(side => (
          <Card key={side.label}>
            <div style={{ padding: '12px 14px', borderBottom: '1px solid var(--border)' }}>
              <div style={{ fontSize: 10, color: side.color, letterSpacing: '0.08em', fontWeight: 600, marginBottom: 6 }}>{side.label}</div>
              <select value={side.model} onChange={e => side.setModel(e.target.value)}
                style={{ width: '100%', padding: '6px 8px', marginBottom: 6, borderRadius: 'var(--radius)', border: '1px solid var(--border-mid)', background: 'var(--bg-raised)', color: 'var(--text-primary)', fontSize: 11, fontFamily: 'var(--font-mono)' }}>
                <option value="">Select model…</option>
                {chatModels.map(m => <option key={m.name} value={m.name}>{m.name}</option>)}
              </select>
              <select value={side.kb} onChange={e => side.setKb(e.target.value)}
                style={{ width: '100%', padding: '6px 8px', borderRadius: 'var(--radius)', border: '1px solid var(--border-mid)', background: 'var(--bg-raised)', color: 'var(--text-primary)', fontSize: 11, fontFamily: 'var(--font-mono)' }}>
                <option value="">No KB (bare model)</option>
                {collections.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
              </select>
            </div>
            <div style={{ padding: '12px 14px', minHeight: 120 }}>
              {side.loading && <div style={{ display: 'flex', justifyContent: 'center', padding: 20 }}><Spinner /></div>}
              {!side.loading && !side.response && <div style={{ fontSize: 11, color: 'var(--text-muted)', textAlign: 'center', padding: 20 }}>Response will appear here</div>}
              {side.response?.error && <div style={{ fontSize: 11, color: 'var(--red)' }}>{side.response.error}</div>}
              {side.response?.reply && (
                <div>
                  <div style={{ fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.6, whiteSpace: 'pre-wrap' }}>{side.response.reply}</div>
                  <div style={{ marginTop: 8, display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                    {side.response.rag && <Badge color="green">RAG used</Badge>}
                    {side.response.tokens && <Badge color="default">{side.response.tokens} tokens</Badge>}
                    {side.response.sources?.slice(0,2).map((s,i) => (
                      <div key={i} style={{ fontSize: 9, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', padding: '1px 6px', background: 'var(--bg-raised)', borderRadius: 4, border: '1px solid var(--border)' }}>
                        {s.source?.split('/').pop()} {(s.relevance*100).toFixed(0)}%
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </Card>
        ))}
      </div>

      <div style={{ display: 'flex', gap: 8 }}>
        <textarea value={prompt} onChange={e => setPrompt(e.target.value)}
          onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); run() } }}
          placeholder="Enter your test prompt… (Enter to send)"
          rows={2}
          style={{ flex: 1, padding: '8px 12px', borderRadius: 'var(--radius-lg)', border: '1px solid var(--border-mid)', background: 'var(--bg-surface)', color: 'var(--text-primary)', fontSize: 12, fontFamily: 'var(--font-mono)', resize: 'none', lineHeight: 1.5 }}
        />
        <Btn variant="accent" onClick={run} disabled={!prompt.trim()}><Send size={13} /></Btn>
      </div>
    </div>
  )
}

// ── Main page ─────────────────────────────────────────────────────────────────
export default function FineTunePage() {
  const { collections, models } = useStore()
  const [tab, setTab] = useState('datasets')

  const TABS = [
    { id: 'datasets', icon: '🗂️', label: 'Dataset Builder' },
    { id: 'jobs',     icon: '⚗️', label: 'Fine-Tune Jobs' },
    { id: 'arena',    icon: '⚔️', label: 'Model Arena' },
  ]

  return (
    <div style={{ animation: 'fadeIn 0.2s ease' }}>
      <PageHelp
        steps={[
          'Dataset Builder: select a KB collection → LLM auto-generates Q&A training pairs',
          'Fine-Tune Jobs: pick a dataset + base model → LoRA training runs in Docker (needs GPU)',
          'After training: export to GGUF → import into Ollama as a new model',
          'Model Arena: compare base model vs fine-tuned model side-by-side on the same prompt',
        ]}
        tips={[
          'RAG is faster and more updatable — use fine-tuning for behavior/style, RAG for knowledge',
          'Start with 3 pairs/chunk, alpaca format, and 3 epochs for most tasks',
          'Dataset generation needs no GPU — just your running Ollama',
          'Fine-tuning the qwen2.5:7b model with LoRA typically needs ~6GB VRAM',
        ]}
      />

      <PageHeader title="Fine-Tune Studio" subtitle="Dataset generation · LoRA training · GGUF export · Model comparison" />

      <Tabs tabs={TABS} active={tab} onChange={setTab} />

      {tab === 'datasets' && <DatasetBuilder collections={collections} models={models} />}
      {tab === 'jobs' && <FineTuneJobs models={models} />}
      {tab === 'arena' && <ModelArena models={models} collections={collections} />}
    </div>
  )
}
